name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CC: clang-14
      CXX: clang++-14

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install build-essential clang-14 llvm-14 lldb-14 lld-14 ninja-build libglu1-mesa-dev freeglut3-dev mesa-common-dev libboost-all-dev libxrandr-dev libxinerama-dev libx11-dev libxcursor-dev libxi-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{github.workspace}} -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} -j4 -T test --output-on-failure

